### ISSUE TITLE
Candidate window is hidden when using input source other than English

### ISSUE THREAD

**Issue by tizee** [KittenYang/ChatGPT-Mac-MenuBar#1]
I found that if using Chinese input source then the candidate window was hidden and it's difficult for me to type Chinese characters. This would affect other non-latin input sources with candidate window.

I also found that this weird behavior only caused by the input text field inside the webview. The native `TextField` works normally with visible candidate window.

I'm not familiar with Swift but I managed to make candidate window visible again by setting the window level of the `statusItem.button` in `AppDelegate.swfit`:

```swift
            button.window?.level = NSWindow.Level.floating
```

But this would cause the app icon hidden on status bar.  I think there is a more elegant approach to fix this but I'm limited by my knowledge of Swift.

**Comment by KittenYang** [comment]
Thanks for reporting.This issue now fixed in Release v1.2.
