### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by tobsn** [KittenYang/ChatGPT-Mac-MenuBar#10]
I just tried the official openAI app and it's okay... then I tried to install your app again but the opanAI app had overwritten it.
Had to install 8 different third party apps to finally find yours, they are all horrible in comparison.

Just wanted to let you know that your app is still the most simple, functional, and cleanest looking.

**Comment by KittenYang** [comment]
@tobsn Very glad to hear that words. Thanks
