### ISSUE TITLE
Add the dmg file as a release asset

### ISSUE THREAD

**Issue by xilopaint** [KittenYang/ChatGPT-Mac-MenuBar#5]
Any reason for having the dmg file in the repo instead as a release asset?

**Comment by KittenYang** [comment]
无语，这是什么弱智提问？我帮你们直接提供了 dmg 还嫌我多事了呗？release asset 又不是自己会生成 dmg，还不是也要手动打包放在 release asset 里。看不懂自己去翻译吧！
